In [3]:
from common.file_handler import read_parquet

In [4]:
from os import listdir

In [2]:
from glob import glob

In [5]:
glob("data/2022-10-01T19-07-52/*.br")

['data/2022-10-01T19-07-52\\AFLW_reddit_comments_2022-10-01T19-08-02.parquet.br',
 'data/2022-10-01T19-07-52\\AFLW_reddit_submissions_2022-10-01T19-08-02.parquet.br',
 'data/2022-10-01T19-07-52\\AFLW_twitter_2022-10-01T19-08-02.parquet.br']

In [12]:
df = read_parquet('data/2022-10-01T19-07-52\\AFLW_twitter_2022-10-01T19-08-02.parquet.br')

In [23]:
fdf = df[df['text'].apply(lambda t: not t.startswith('RT'))]

In [24]:
fdf

,tweet_id,text,created_at,retweet_count,reply_count,like_count,quote_count
3,1573892141897682947,https://t.co/IasoCEZLWe,2022-09-25 04:28:22+00:00,0,0,0,0
7,1573891935282122756,@delarosanyc @ReynaJerez89 @EuricSanti Esa mis...,2022-09-25 04:27:33+00:00,0,0,0,0
16,1573891705296007168,#AlbertPujols #MLB #baseball #Literature #poet...,2022-09-25 04:26:38+00:00,0,0,0,0
19,1573891631127973888,@estonoesradioTW Nicole Fernández es una engre...,2022-09-25 04:26:21+00:00,0,0,0,0
21,1573891598588354561,プホルスの700号のボールをゲットしたファンはそのボールが700号のものであると認証されたあ...,2022-09-25 04:26:13+00:00,1,0,6,0
...,...,...,...,...,...,...,...
9974,1573754110393860096,I keep thinking that if Albert Pujols went to ...,2022-09-24 19:19:53+00:00,0,0,0,0
9976,1573754095936196613,*LEONEL GANA PRESIDENCIA EN 2024*\n\nALBERT PU...,2022-09-24 19:19:50+00:00,10,2,69,4
9981,1573754053754060802,@miklasz I did enjoy. Did you know the first ...,2022-09-24 19:19:40+00:00,0,0,0,0
9983,1573754016504356867,@EclectikSports @sports_sell @MDRANSOM1 @Hobby...,2022-09-24 19:19:31+00:00,2,0,3,0
9997,1573753896329269248,#Albert Pujols 700 home runs: Cardinals legend...,2022-09-24 19:19:02+00:00,0,0,0,0

In [13]:
df

,tweet_id,text,created_at,retweet_count,reply_count,like_count,quote_count
0,1576166141911007235,@ToddJDavey Didn’t cost them the game and does...,2022-10-01 11:04:26+00:00,0,0,0,0
1,1576166039855202304,AFLW: Richmond d Gold Coast Suns: Crowd TBA @ ...,2022-10-01 11:04:02+00:00,0,0,0,0
2,1576165935706083328,Men should be banned from commenting on the AF...,2022-10-01 11:03:37+00:00,0,0,0,0
3,1576165555454689280,"Yeah, tell me again about that “quality” produ...",2022-10-01 11:02:06+00:00,0,0,0,0
4,1576165508642385921,As a man ‘slightly’ beyond middle age I am pri...,2022-10-01 11:01:55+00:00,0,1,2,0
...,...,...,...,...,...,...,...
95,1576145685392818176,Tigers player drops footy cold yet wins free k...,2022-10-01 09:43:09+00:00,0,0,1,0
96,1576145127524880385,Switch to 73 expecting some action movie and I...,2022-10-01 09:40:56+00:00,0,1,1,0
97,1576145111590662144,@ToddJDavey Difference is the fact that this ...,2022-10-01 09:40:52+00:00,0,0,0,0
98,1576144786146222080,@NadineRabah25 Send the video to #Pricey \nAs ...,2022-10-01 09:39:35+00:00,0,0,0,0
99,1576144669204889601,The WAFL in WA has been going for 138 yrs . Ho...,2022-10-01 09:39:07+00:00,2,0,7,0

In [27]:
df1 = read_parquet(r'./data\2022-09-25T22-36-16\Wisconsin vs Ohio State_2022-09-25T22-36-18.parquet.br')
df1

,tweet_id,text,created_at,retweet_count,reply_count,like_count,quote_count
0,1574044971820261377,Ohio State had 821 total Yards of Offense vs. ...,2022-09-25 14:35:40+00:00,0,0,0,0
1,1574044525332496390,Ryan Day is hopeful Ohio State's injured playe...,2022-09-25 14:33:53+00:00,0,0,0,0
2,1574039784246415365,Ohio State WR Julian Fleming 1st Down &amp; TD...,2022-09-25 14:15:03+00:00,0,0,0,0
3,1574038619756511236,Watch: Ohio State’s Mascot Gets Rocked During ...,2022-09-25 14:10:25+00:00,0,0,0,0
4,1574038610453491712,Watch: Ohio State’s Mascot Gets Rocked During ...,2022-09-25 14:10:23+00:00,0,0,0,0
...,...,...,...,...,...,...,...
95,1573885295837192192,"Ohio State vs. Wisconsin score, takeaways: No....",2022-09-25 04:01:10+00:00,0,0,0,0
96,1573883505431674880,Ryan Day addresses Jaxon Smith-Njigba’s absenc...,2022-09-25 03:54:03+00:00,1,0,14,0
97,1573882341402943490,Final in Columbus.\n\nMore at: https://t.co/zt...,2022-09-25 03:49:26+00:00,28,2,436,3
98,1573882068374900737,Wisconsin #Badgers vs. No. 3 Ohio State game r...,2022-09-25 03:48:21+00:00,2,1,5,0
99,1573881817232556032,"Ohio State vs. Wisconsin score, takeaways: No....",2022-09-25 03:47:21+00:00,0,0,0,0

In [29]:
df1.sort_values(['like_count', 'retweet_count'])

,tweet_id,text,created_at,retweet_count,reply_count,like_count,quote_count
0,1574044971820261377,Ohio State had 821 total Yards of Offense vs. ...,2022-09-25 14:35:40+00:00,0,0,0,0
1,1574044525332496390,Ryan Day is hopeful Ohio State's injured playe...,2022-09-25 14:33:53+00:00,0,0,0,0
2,1574039784246415365,Ohio State WR Julian Fleming 1st Down &amp; TD...,2022-09-25 14:15:03+00:00,0,0,0,0
3,1574038619756511236,Watch: Ohio State’s Mascot Gets Rocked During ...,2022-09-25 14:10:25+00:00,0,0,0,0
4,1574038610453491712,Watch: Ohio State’s Mascot Gets Rocked During ...,2022-09-25 14:10:23+00:00,0,0,0,0
...,...,...,...,...,...,...,...
69,1573907844499243008,"Once again, @ryandaytime hopes to have @jaxon_...",2022-09-25 05:30:46+00:00,2,1,13,0
96,1573883505431674880,Ryan Day addresses Jaxon Smith-Njigba’s absenc...,2022-09-25 03:54:03+00:00,1,0,14,0
84,1573891817308770305,WATCH: @TBDBITL's pregame show before #OhioSta...,2022-09-25 04:27:05+00:00,2,0,18,0
19,1574021420442451968,Let's check in on the Michigam fans while they...,2022-09-25 13:02:05+00:00,28,31,365,10
97,1573882341402943490,Final in Columbus.\n\nMore at: https://t.co/zt...,2022-09-25 03:49:26+00:00,28,2,436,3